# language: php
# tests: true

filter:
  excluded_paths:
    - "examples/"
    - "resources/"
    - "tests/"

tools:
  external_code_coverage:
    runs: 4

coding_style:
  php:
    indentation:
      general:
        use_tabs: false
        size: 4

build:
  nodes:
    tests: true
    analysis:
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true
          - php-scrutinizer-run

checks:
  php:
    code_rating: true
    duplication: false
